<?php
$oXML = $block->getExchangerates();
?>


<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>exchangrates</title>
</head>
<body>
    <p style="font-size: 12px;color:#da1d2a"><?= $oXML->pubDate ?></p>
<table style="font-size: 12px" class="table table-hover">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">inverseDescription</th>
        <th scope="col">description</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $i = 1;
    foreach ($oXML->item as $value) { ?>
    <tr>
        <td><?php echo $i; $i++ ?></td>
        <td><?= $value->inverseDescription ?></td>
        <td><?=$value->description ?></td>
    </tr>
 <?php }?>

    </tbody>
</table>
</body>
</html>


