<?php
$json=$block->getWeather();
$data=json_decode($json);

$arrTime=$block->updateTime();
 $time= $arrTime['time'];
 $day=$arrTime['day'];
 $date=$arrTime['date'];
?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Wether</title>
    <style>
        body {
            color: #fff;
            overflow-x: hidden;
            height: 100%;
            background-image: linear-gradient(#81D4FA, #2196F3);
            background-repeat: no-repeat


        }

        .card0 {
            width: 94%
        }

        .card1 {


            padding: 30px 20px 30px 50px
        }

        .image {
            width: 300px;
            height: 300px
        }

        .large-font {
            font-size: 70px;
            font-family: Arial
        }

        .fa-sun-o {
            font-size: 22px
        }

        .card2 {
            background-color: #607D8B;
            padding: 0px 0px 40px 40px
        }

        input {
            background-color: #607D8B;
            padding: 24px 0px 12px 0px !important;
            width: 80%;
            box-sizing: border-box;
            border: none !important;
            border-bottom: 1px solid #CFD8DC !important;
            font-size: 16px !important;
            color: #fff !important
        }

        input:focus {
            -moz-box-shadow: none !important;
            -webkit-box-shadow: none !important;
            box-shadow: none !important;
            border-bottom: 1px solid #fff !important;
            outline-width: 0;
            font-weight: 400
        }

        ::placeholder {
            color: #B0BEC5 !important;
            opacity: 1
        }

        :-ms-input-placeholder {
            color: #B0BEC5 !important
        }

        ::-ms-input-placeholder {
            color: #B0BEC5 !important
        }

        .fa-search {
            color: #607D8B;
            background-color: #E1F5FE;
            font-size: 20px;
            padding: 20px;
            width: 20%;
            cursor: pointer
        }

        .light-text {
            color: #B0BEC5
        }

        .suggestion:hover {
            color: #fff;
            cursor: pointer
        }

        .line {
            height: 1px;
            background-color: #B0BEC5
        }

        @media screen and (max-width: 500px) {
            .card1 {
                padding-left: 26px
            }
        }
    </style>
    <link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
</head>
<body>

<script src='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<div class="container-fluid px-1 px-sm-3 py-5 mx-auto">
    <div style="width: 945px;height: 500px;" class="row d-flex justify-content-center">
        <div class="row card0">
            <div id="weather"  class="card1 col-lg-8 col-md-7" style="background-image:url('https://images-na.ssl-images-amazon.com/images/I/51y6dy0T8sL._AC_SL1000_.jpg');"> <small>the.weather</small>
<!--                    <div class="text-center"> <img class="image mt-5" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Sun-soleil2.svg/500px-Sun-soleil2.svg.png"> </div>-->
                <div class="row px-3 mt-3 mb-3">
                    <h1 class="large-font mr-3"><?= $data->main->temp-273.15;?>&#176;</h1>
                    <div class="d-flex flex-column mr-3">
                        <h2 class="mt-3 mb-0"><?= $data->name;?></h2> <small style="font-size: 130%"><?=$time." ".$date; ?></small>
                    </div>
                    <div class="d-flex flex-column text-center">
                        <h3 class="fa fa-sun-o mt-4"></h3> <small style="font-size: 130%"><?=$day; ?></small>
                    </div>
                </div>
            </div>
            <div style="font-size: 15px" class="card2 col-lg-4 col-md-5">
                <!--                <div class="row px-3"> <input type="text" name="location" placeholder="Another location" class="mb-5">-->
                <!--                    <div class="fa fa-search mb-5 mr-0 text-center"></div>-->
                <!--                </div>-->
                <div class="mr-5">

                    <p style="font-size: 20px">Weather Details</p>
                    <div class="row px-3">
                        <p style="color:#dcaa35" class="light-text">main</p>
                        <p id="main" style="color:#dcaa35" class="ml-auto"><?= $data->weather[0]->main;?></p>
                    </div>
                    <div class="row px-3">
                        <p style="color:#dcaa35" class="light-text">des</p>
                        <p id="des" style="color:#dcaa35" class="ml-auto"><?= $data->weather[0]->description; ?></p>
                        <script>
                                var  des=document.getElementById('des').innerHTML;
                                if (des=="broken clouds")
                                    document.getElementById('weather').setAttribute("style", "background-image: url('https://shiftyjelly.files.wordpress.com/2013/11/w.jpg?w=750&h=425')");
                                var  main=document.getElementById('main').innerHTML;
                                if(main=="rain"){
                                    document.getElementById('weather').setAttribute("style", "background-image: url('https://lh3.googleusercontent.com/tWCIaaJGSkoDZr-fvhzAZJabCJun_gUzwCXtlvDJoDDXgsUg8bVNOiyp6_qa4-aaksyC2U-VYuRfuur7I3q4NpHxMVgaPzjtfJ71jMZX6EYPd8OKIwmhlSy8J8QO9OnXzfYVPG0H1T6aAH33JG6zezcU1nBijyFYsVXJBnQMuBIEeL3Y7i4nSOBLq2woEl7n6NTLERuy4AA5btfDPFiFKi1YDlD1cndVIjSjQtR3EmBQ_LOj2VRZo9kyGulDRGHvzfsgfT7LXNobBxmjKpRXLuX2S7gR47pChc_ff-0cOb0DQGB4aBusxR82A7-w7cd8rgW_e48bGBqqemPU1crpvT0bMTeRhemqd_S0nmMRbT25NohC23NHw09OFYs5_yKCrSuFEYvxJtOva6bvId5QKnVzyAK4JS3rtkT8VERDoK6EERbEii9wZNJ5A1YwAqht2jBbOqDK7HyFD1d0cCnYNXEPN1nLp_xoSJNAo-M3dsu-VHmDUvO9xhlw32BDsOFNnu3sz4gra1CBQzlU7SVcvQkH81xYesxj6TCau2bp6RNxl-NvQk__Ni0PNsyJ5al3D4HTk-so-fNlbbP7NhCNdXhHK9pjtMPmhJBdI4VxMc80KJsnn_KT6Q=w1516-h853-no?.jpg')");
                                    document.getElementsByTagName('body')[0].setAttribute("style","background-image: linear-gradient(#7d7d7d, #666)");
                                }
                        </script>
                    </div>

                    <div class="line mt-3"></div>
                    <div class="row px-3">
                        <p class="light-text">feels_like</p>
                        <p class="ml-auto"><?= $data->main->feels_like-273.15;?>&#176;</p>
                    </div>
                    <div class="row px-3">
                        <p class="light-text">temp_max</p>
                        <p class="ml-auto"><?= $data->main->temp_max-273.15;?>&#176;</p>
                    </div>
                    <div class="row px-3">
                        <p class="light-text">temp_min</p>
                        <p class="ml-auto"><?= $data->main->temp_min-273.15;?>&#176;</p>
                    </div>
                    <div class="row px-3">
                        <p class="light-text">wind speed</p>
                        <p class="ml-auto"><?=$data->wind->speed ?>m/s</p>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

</body>

</html>
